#ifndef GRANTS_AND_FUNDING_FIELDS_H
#define GRANTS_AND_FUNDING_FIELDS_H

enum grantsAndFundingField { 
  MEMBER_NAME,
  PRIMARY_DOMAIN,
  START_DATE,
  END_DATE,
  FUNDING_TYPE,
  STATUS,
  PEER_REVIEWED,
  INDUSTRY_GRANT,
  ROLE,
  TITLE,
  PRINCIPAL_INVESTIGATOR,
  CO_INVESTIGATORS,
  TOTAL_AMOUNT,

  DATES,

  PUBLICATION_STATUS,
  STATUS_DATE,
  TYPE,
  JOURNAL_NAME,
  AUTHOR,
  
  PROGRAM,
  TYPE_OF_COURSE,
  GEOGRAPHICAL_SCOPE,
  HOURS_PER_SESSION_OR_WEEK,
  NUMBER_OF_SESSIONS_OR_WEEKS,
  TOTAL_HOURS
};
 
#endif
